### status: runtime-confirmed
### public: false
### authRequired: true
### destructive: true
### requiresTenantHeaders: true

@baseUrl = https://praxis-api-quickstart.onrender.com
@tenantId = demo
@userId = example-user
@envId = public

POST {{baseUrl}}/api/human-resources/funcionarios
Content-Type: application/json
Accept: application/json
X-Tenant-ID: {{tenantId}}
X-User-ID: {{userId}}
X-Env: {{envId}}

< ../../payloads/resources/funcionarios_create.json
