### status: runtime-confirmed,recommended
### public: false
### authRequired: true
### sessionAuthRequired: false
### tenantScopedHeadersRequired: true
### destructive: false
### requiresTenantHeaders: true
### llmOperational: false
### protectedContract: false
### referenceOnly: true
### runtimeRecordConfirmed: true
### selectorConfirmed: true
### publishedBackendConfirmed: false
### knownPublishedFailure: false
### selectionGuidance: avoid-by-default-reference

@baseUrl = https://praxis-api-quickstart.onrender.com
@tenantId = demo
@userId = example-user
@envId = public

POST {{baseUrl}}/api/human-resources/funcionarios/locate?id=1&size=10
Content-Type: application/json
Accept: application/json
X-Tenant-ID: {{tenantId}}
X-User-ID: {{userId}}
X-Env: {{envId}}

< ../../payloads/resources/funcionarios_filter_basic.json
