### status: runtime-confirmed,recommended
### public: false
### authRequired: true
### destructive: false
### requiresTenantHeaders: true

@baseUrl = https://praxis-api-quickstart.onrender.com
@tenantId = demo
@userId = example-user
@envId = public

POST {{baseUrl}}/api/human-resources/vw-ranking-reputacao/filter/cursor?size=10
Content-Type: application/json
Accept: application/json
X-Tenant-ID: {{tenantId}}
X-User-ID: {{userId}}
X-Env: {{envId}}

< ../../payloads/views/vw_ranking_reputacao_filter_basic.json
