### status: none
### public: false
### authRequired: true
### sessionAuthRequired: false
### tenantScopedHeadersRequired: true
### destructive: true
### requiresTenantHeaders: true
### llmOperational: false
### protectedContract: true
### referenceOnly: false
### runtimeRecordConfirmed: false
### selectorConfirmed: true
### publishedBackendConfirmed: false
### knownPublishedFailure: false
### selectionGuidance: protected-contract-write

@baseUrl = https://praxis-api-quickstart.onrender.com
@tenantId = demo
@userId = demo-user-1
@envId = local

PUT {{baseUrl}}/api/praxis/config/ui?componentType=praxis-dynamic-form&componentId=praxis-form-config-employee-form:edit&scope=user
Content-Type: application/json
Accept: application/json
X-Tenant-ID: {{tenantId}}
X-User-ID: {{userId}}
X-Env: {{envId}}

< ../../payloads/config/ui_put_form.json
