### status: none
### public: false
### authRequired: true
### sessionAuthRequired: false
### tenantScopedHeadersRequired: true
### destructive: true
### requiresTenantHeaders: true
### llmOperational: false
### protectedContract: true
### referenceOnly: false
### runtimeRecordConfirmed: false
### selectorConfirmed: true
### publishedBackendConfirmed: false
### knownPublishedFailure: false
### selectionGuidance: protected-contract-write

@baseUrl = https://praxis-api-quickstart.onrender.com
@tenantId = tenant-abc
@envId = local

PUT {{baseUrl}}/api/praxis/config/ui?componentType=praxis-global-config-editor&componentId=praxis:global-config:tenant-abc&scope=tenant
Content-Type: application/json
Accept: application/json
X-Tenant-ID: {{tenantId}}
X-Env: {{envId}}

< ../../payloads/config/ui_put_global_config.json
